{
    "name": "Hospital Management",
    "version": "1.0",
    "category": "Management/Management",
    "summary": "Hospital Management System",
    "author": "BizzAppDev",
    "description": """
    This module contains all the common features of Hospital Management.
    """,
    "depends": ["base", "mail", "hr", "product", "sale_management", "stock", "account"],
    "data": [
        "security/ir.model.access.csv",
        "security/security.xml",
        "wizard/create_appointment_view.xml",
        "wizard/appointment_report_view.xml",
        "wizard/search_appointment_view.xml",
        "wizard/hospital_appointments_invoice_wizard_view.xml",
        "views/patient_view.xml",
        "views/doctor_view.xml",
        "views/department_view.xml",
        "views/appointment_view.xml",
        "views/medicaltest_view.xml",
        "views/inpatient_view.xml",
        "views/bed_transfer_view.xml",
        "views/menu_view.xml",
        "report/appointment_report_template.xml",
        "report/report_patient.xml",
        "data/appointment_seq.xml",
        "data/cron.xml",
        "data/mail_template.xml",
        "data/checkup_remainder_email_template.xml",
    ],
    "demo": [],
    "installable": True,
    "auto_install": False,
    "license": "LGPL-3",
}
