from . import school_students
from . import school_teachers
from . import students_results
from . import school_attendance
from . import school_assignment
from . import school_library
from . import school_parents
from . import academic_holidays
from . import assignment_submit
from . import exam_timetable
from . import school_admission
from . import school_fees
from . import school_timetable
from . import fees_structure
from . import timetable_structure
from . import about_us
from . import home_page
from . import inherit_sale_order
from . import inherit_invoice
from . import inherit_sale_order_line
from . import inherit_stock_picking
from . import inherit_stock_move
from . import inherit_project
from . import inherit_purchase
from . import inherit_manufracture
from . import inherit_stock_rule